### ISSUE TITLE
GraXpert failed

### ISSUE THREAD

**Issue by Nagant132017** [DeepSkyForge/GraXpert4PixInsight#30]
Hello, I have trouble with GraXpert in Pixinsight and I could not find same error in internet.
I don't know whether writing my issue here is right or wrong but I beg your help.
The error message is like below.

run --execute-mode=auto "/Applications/PixInsight/src/scripts/Toolbox/Graxpert.js"

Processing script file: /Applications/PixInsight/src/scripts/Toolbox/Graxpert.js
Reading previously used settings from /Users/Nagant/Library/Application Support/GraXpertScript/GraXpertScript.json

PixelMath: Processing view: Light_M13_30_0s_Bin1_B_gain100_20240413_225207_10_1C_0003
Executing PixelMath expression:
$T
channel #0: done
Truncating to [0,1]: done
190.771 ms
Temporary image file: /var/folders/rc/rf3lh9bn4ms1qltgf03_dzy40000gn/T/Light_M13_30_0s_Bin1_B_gain100_20240413_225207_10_1C_0003_GraXpertImage.xisf

Writing file:
/var/folders/rc/rf3lh9bn4ms1qltgf03_dzy40000gn/T/Light_M13_30_0s_Bin1_B_gain100_20240413_225207_10_1C_0003_GraXpertImage_Temp.xisf
Writing image: w=3008 h=3008 n=1 Gray UInt16
1 image property embedded
running "/Applications/GraXpert.app" -cli "/var/folders/rc/rf3lh9bn4ms1qltgf03_dzy40000gn/T/Light_M13_30_0s_Bin1_B_gain100_20240413_225207_10_1C_0003_GraXpertImage_Temp.xisf" -correction Subtraction -smoothing 0
starting GraXpert...
2024-05-21 10:12:29,163 MainProcess root INFO     Starting GraXpert CLI, Background-Extraction, version: 3.0.2 release: Umbriel

2024-05-21 10:12:30,175 MainProcess root INFO     Using AI version 1.0.1. 

2024-05-21 10:12:30,177 MainProcess root INFO     Excecuting background extraction with the following parameters:
interpolation type - AI
         smoothing - 0.0
   correction type - Subtraction
     AI model path - /Users/Nagant/Library/Application Support/GraXpert/bge-ai-models/1.0.1/model.onnx
2024-05-21 10:12:30,199 MainProcess root ERROR    Traceback (most recent call last):
2024-05-21 10:12:30,200 MainProcess root ERROR      File "graxpert/main.py", line 298, in 
2024-05-21 10:12:30,200 MainProcess root ERROR      File "graxpert/main.py", line 278, in main
2024-05-21 10:12:30,200 MainProcess root ERROR      File "graxpert/cmdline_tools.py", line 153, in execute
2024-05-21 10:12:30,200 MainProcess root ERROR      File "graxpert/background_extraction.py", line 75, in extract_background
2024-05-21 10:12:30,200 MainProcess root ERROR      File "onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
2024-05-21 10:12:30,200 MainProcess root ERROR      File "onnxruntime/capi/onnxruntime_inference_collection.py", line 460, in _create_inference_session
2024-05-21 10:12:30,200 MainProcess root ERROR    onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from /Users/Nagant/Library/Application Support/GraXpert/bge-ai-models/1.0.1/model.onnx failed:Load model /Users/Nagant/Library/Application Support/GraXpert/bge-ai-models/1.0.1/model.onnx failed. File doesn't exist
[32825] Failed to execute script 'main' due to unhandled exception: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from /Users/Nagant/Library/Application Support/GraXpert/bge-ai-models/1.0.1/model.onnx failed:Load model /Users/Nagant/Library/Application Support/GraXpert/bge-ai-models/1.0.1/model.onnx failed. File doesn't exist
[32825] Traceback:
Traceback (most recent call last):
  File "graxpert/main.py", line 298, in 
  File "graxpert/main.py", line 278, in main
  File "graxpert/cmdline_tools.py", line 153, in execute
  File "graxpert/background_extraction.py", line 75, in extract_background
  File "onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
  File "onnxruntime/capi/onnxruntime_inference_collection.py", line 460, in _create_inference_session
onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from /Users/Nagant/Library/Application Support/GraXpert/bge-ai-models/1.0.1/model.onnx failed:Load model /Users/Nagant/Library/Application Support/GraXpert/bge-ai-models/1.0.1/model.onnx failed. File doesn't exist

GraXpert finished...

ScreenTransferFunction: Processing view: Light_M13_30_0s_Bin1_B_gain100_20240413_225207_10_1C_0003
49.342 ms

Even though the console said to me that the GraXpert has been finished, I could not find any background model or changed image.
Thank you.

**Comment by DeepSkyForge** [comment]
Hi,

You describe a problem in GraXpert Toolbox Script.
This website is dedicated to GraXpert Process available here: https://www.deepskyforge.com/
Nevertheless, you can follow the FAQ I wrote here: https://github.com/DeepSkyForge/GraXpert4PixInsight/wiki/AI-model-file-doesn't-exist
I hope this help!
