### ISSUE TITLE
Unable to Use GraXpert in PI since updating to 3.0

### ISSUE THREAD

**Issue by VinnyVent84** [DeepSkyForge/GraXpert4PixInsight#9]
Hi hopefully someone can help me out. I updated both my windows and Mac laptops to the new GraXpert 3.0 this morning. The standalone program works fine on both, including downloading of the denoise AI. The problem is when I would go to use the Background Extractor tool I would receive the following error in the screenshot attached from PI. I completely uninstalled GraXpert and removed the link from the PI Repository. Rebooted; reinstalled GraXpert 3.0 and downloaded AI model again. Added the following link to the repository again (https://pixinsight.deepskyforge.com/update/graxpert-process/) - problem is when I hit check for updates it says there are no new updates. So I can no longer use or see Graxpert in PI on my windows laptop.

I have yet to remove / redownload and install GraXpert as a means of troubleshooting on Mac yet; the AI Denoise works fine as a script but on my mac I get the following error when trying to perform a background extraction in PI:

**starting GraXpert...

2024-04-24 20:56:03,094 MainProcess root INFO Starting GraXpert CLI, Background-Extraction, version: 3.0.0 release: Umbriel

2024-04-24 20:56:03,593 MainProcess root INFO Using AI version 1.0.1. 

2024-04-24 20:56:03,593 MainProcess root INFO Excecuting background extraction with the following parameters:

interpolation type - AI

smoothing - 0.0

correction type - Subtraction

AI model path - /Users/vinnyv./Library/Application Support/GraXpert/bge-ai-models/1.0.1/model.onnx

2024-04-24 20:56:03,700 MainProcess root ERROR Traceback (most recent call last):

2024-04-24 20:56:03,700 MainProcess root ERROR File "graxpert/main.py", line 293, in 

2024-04-24 20:56:03,700 MainProcess root ERROR File "graxpert/main.py", line 273, in main

2024-04-24 20:56:03,700 MainProcess root ERROR File "graxpert/cmdline_tools.py", line 145, in execute

2024-04-24 20:56:03,700 MainProcess root ERROR File "graxpert/background_extraction.py", line 75, in extract_background

2024-04-24 20:56:03,700 MainProcess root ERROR File "onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__

2024-04-24 20:56:03,700 MainProcess root ERROR File "onnxruntime/capi/onnxruntime_inference_collection.py", line 460, in _create_inference_session

2024-04-24 20:56:03,700 MainProcess root ERROR onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from /Users/vinnyv./Library/Application Support/GraXpert/bge-ai-models/1.0.1/model.onnx failed:Load model /Users/vinnyv./Library/Application Support/GraXpert/bge-ai-models/1.0.1/model.onnx failed. File doesn't exist

[47311] Failed to execute script 'main' due to unhandled exception: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from /Users/vinnyv./Library/Application Support/GraXpert/bge-ai-models/1.0.1/model.onnx failed:Load model /Users/vinnyv./Library/Application Support/GraXpert/bge-ai-models/1.0.1/model.onnx failed. File doesn't exist

[47311] Traceback:

Traceback (most recent call last):

File "graxpert/main.py", line 293, in 

File "graxpert/main.py", line 273, in main

File "graxpert/cmdline_tools.py", line 145, in execute

File "graxpert/background_extraction.py", line 75, in extract_background

File "onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__

File "onnxruntime/capi/onnxruntime_inference_collection.py", line 460, in _create_inference_session

onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from /Users/vinnyv./Library/Application Support/GraXpert/bge-ai-models/1.0.1/model.onnx failed:Load model /Users/vinnyv./Library/Application Support/GraXpert/bge-ai-models/1.0.1/model.onnx failed. File doesn't exist

GraXpert finished...

*** Error [000]: /Applications/PixInsight/src/scripts/Toolbox/Graxpert.js, line 670: Error: ImageWindow.Set(): null image window**

So at this point I cannot use GraXpert background extractor on either machine - can someone please advise?

![Screenshot 2024-04-24 201125](https://github.com/DeepSkyForge/GraXpert4PixInsight/assets/168046401/d3d4cd44-87d6-4968-9111-cc0e2f680ddc)

**Comment by DeepSkyForge** [comment]
Hi [VinnyVent84](https://github.com/VinnyVent84)

For "problem is when I hit check for updates it says there are no new updates",
the only solution I found, when I'm facing such situation with scripts/process update, is to reset updates.
From PixInsight:
1. Click RESOURCES > Updates > Reset updates
2. Confirm
3. Restart PixInsight
4. Click RESOURCES > Updates > Check for Updates (or wait PixInsight notify updates available)
5. Select Updates you want to apply (or keep all selected)
6. Apply Update
7. Restart PixInsight
You should have GraXpert process back in the Menu PROCESS > Etc

For the "/Users/vinnyv./Library/Application Support/GraXpert/bge-ai-models/1.0.1/model.onnx failed. File doesn't exist"
This is a known issue when you upgrade to GraXpert 3.0.0.
Please refer to case https://github.com/DeepSkyForge/GraXpert4PixInsight/issues/1
I'm waiting confirmation of resolution before to close it.

Regards

**Comment by VinnyVent84** [comment]
Thank you very much for the fast reply! I have followed your exact instructions outlined below for the windows machine but sadly it's still not working. I think I failed to mention in the initial comments that when I uninstalled GraXpert the first time I not only removed it from the Repository but also removed it from the scripts by going to Script > Feature Scripts > Uncheck the GraXpert Boxes. Not sure if that makes a difference to know.

When I followed your steps it seemed like it was working as everything had to redownload and GraXpert did show up as an installed update - odd thing is its still not available in Toolbox at all. I even went to add the script manually but in the PI src folder there is no Graxpert folder. I have tried to attached the relevant screenshots for your review. Thanks in advance for any additional guidance you can give.
________________________________

**Comment by DeepSkyForge** [comment]
Oops sorry, my answer was for GraXpert Process (https://www.deepskyforge.com/index.html).
After install of process you should have GraXpert in PROCESS > Etc.

For GraXpert script from Toolbox (https://www.ideviceapps.de/PixInsight/Utilities/), please contact developper of the script.

Problem related to "GraXpert/bge-ai-models/1.0.1/model.onnx failed. File doesn't exist" is common for both scripts so you can apply #1.

**Comment by VinnyVent84** [comment]
Sorry for the initial confusion on my part - I did follow your steps and did go to the process section; as you stated it the tool is now there which is great. However I do still get the error in the attached screenshot when trying to run the background extraction. Is there anything else I can try?
________________________________

**Comment by DeepSkyForge** [comment]
Ok good.
For the problem displayed in screenshot "... model.onnx failed. File doesn't exist",
this is a known issue in GraXpert 3.x when you upgrade from GraXpert 2.x.
I described the process to fix it in case #1 
Basically, you have to remove all AI models and process an image with GraXpet 3.x to force upload of new models.
All is described, step by step in case #1 ;-)

**Comment by DeepSkyForge** [comment]
I close this known issue. Community already confirm that removing old AI fix the issue in GraXpert.
Do not hesitate to come back to me if you need additional help.
Regards
